### ISSUE TITLE
Fazer novo diagrama de classes para o package Domain

### ISSUE THREAD

**Issue by Petreko** [Petreko/tcc_pedro_vitor#29]
Como desenvolvedores & analistas, precisamos fazer um novo diagrama de classes, para podermos gerar um código eficiente e compreensível.

**Comment by Petreko** [comment]
@Vitortrn e @arturbrandt, depois de fazermos novos levantamentos para o sistema, percebemos que só será necessário salvar a simulação com os arquivos no banco de dados, não mais será necessário salvar todas as ocorrências dos átomos e das ligações individualmente.

**Comment by Petreko** [comment]
@Vitortrn, dê uma olhada neste alternativa para o astah (ela é gratuíta): http://plantuml.com/

**Comment by arturbrandt** [comment]
Interessante. Podem ir em frente!

Aproveitando:
Nesta quinta vou viajar e só retorno dia 27. Portanto, se não responder vcs
é por esse motivo. Se não der pra responder durante a viajem eu respondo
quando voltar.

Abs

Em ter, 9 de jul de 2019 às 18:50, Pedro Lívio <notifications@github.com>
escreveu:

**Comment by Petreko** [comment]
Ok.

Boa viagem, professor.

Em ter, 9 de jul de 2019 19:08, Artur Brandt <notifications@github.com>
escreveu:

**Comment by Petreko** [comment]
@Vitortrn, dê uma olhada neste diagrama de classes e me diga a tua opinião (usei o PlanUML): 
![tcc_pedro_vitor_diagrama_classes_po](https://user-images.githubusercontent.com/30321602/61020888-a23e3e00-a375-11e9-9010-b2a9bd04a4af.png)
