### ISSUE TITLE
Avaliar se devemos usar Milestones ou Releases para representar a iteração no Zenhub

### ISSUE THREAD

**Issue by Petreko** [Petreko/tcc_pedro_vitor#34]
Como desenvolvedores & analistas, precisamos saber qual a melhor prática para representar uma iteração no Zenhub, para sermos eficientes.

**Comment by Vitortrn** [comment]
https://help.zenhub.com/support/solutions/articles/43000010360

**Comment by Petreko** [comment]
@Vitortrn, pelo o que discutimos, nós poderemos usar tanto a release quanto a milestone em nosso projeto.
A release será usada para representar versões do nosso sistema, e a milestone para representar a nosso iteração.
